/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as RevisionPolizaRouteImport } from './routes/revision-poliza'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as IndustriasRouteImport } from './routes/industrias'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegurosCondominioRouteImport } from './routes/seguros.condominio'
import { Route as SegurosColegiosRouteImport } from './routes/seguros.colegios'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionPolizaRoute = RevisionPolizaRouteImport.update({
  id: '/revision-poliza',
  path: '/revision-poliza',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriasRoute = IndustriasRouteImport.update({
  id: '/industrias',
  path: '/industrias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosCondominioRoute = SegurosCondominioRouteImport.update({
  id: '/seguros/condominio',
  path: '/seguros/condominio',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosColegiosRoute = SegurosColegiosRouteImport.update({
  id: '/seguros/colegios',
  path: '/seguros/colegios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/industrias': typeof IndustriasRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/privacidad': typeof PrivacidadRoute
  '/productos': typeof ProductosRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/revision-poliza': typeof RevisionPolizaRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/seguros/colegios': typeof SegurosColegiosRoute
  '/seguros/condominio': typeof SegurosCondominioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/industrias': typeof IndustriasRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/privacidad': typeof PrivacidadRoute
  '/productos': typeof ProductosRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/revision-poliza': typeof RevisionPolizaRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/seguros/colegios': typeof SegurosColegiosRoute
  '/seguros/condominio': typeof SegurosCondominioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/industrias': typeof IndustriasRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/privacidad': typeof PrivacidadRoute
  '/productos': typeof ProductosRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/revision-poliza': typeof RevisionPolizaRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/seguros/colegios': typeof SegurosColegiosRoute
  '/seguros/condominio': typeof SegurosCondominioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/industrias'
    | '/preguntas-frecuentes'
    | '/privacidad'
    | '/productos'
    | '/quienes-somos'
    | '/revision-poliza'
    | '/servicios'
    | '/sitemap.xml'
    | '/terminos'
    | '/seguros/colegios'
    | '/seguros/condominio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/industrias'
    | '/preguntas-frecuentes'
    | '/privacidad'
    | '/productos'
    | '/quienes-somos'
    | '/revision-poliza'
    | '/servicios'
    | '/sitemap.xml'
    | '/terminos'
    | '/seguros/colegios'
    | '/seguros/condominio'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/industrias'
    | '/preguntas-frecuentes'
    | '/privacidad'
    | '/productos'
    | '/quienes-somos'
    | '/revision-poliza'
    | '/servicios'
    | '/sitemap.xml'
    | '/terminos'
    | '/seguros/colegios'
    | '/seguros/condominio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  IndustriasRoute: typeof IndustriasRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ProductosRoute: typeof ProductosRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  RevisionPolizaRoute: typeof RevisionPolizaRoute
  ServiciosRoute: typeof ServiciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminosRoute: typeof TerminosRoute
  SegurosColegiosRoute: typeof SegurosColegiosRoute
  SegurosCondominioRoute: typeof SegurosCondominioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision-poliza': {
      id: '/revision-poliza'
      path: '/revision-poliza'
      fullPath: '/revision-poliza'
      preLoaderRoute: typeof RevisionPolizaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrias': {
      id: '/industrias'
      path: '/industrias'
      fullPath: '/industrias'
      preLoaderRoute: typeof IndustriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros/condominio': {
      id: '/seguros/condominio'
      path: '/seguros/condominio'
      fullPath: '/seguros/condominio'
      preLoaderRoute: typeof SegurosCondominioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros/colegios': {
      id: '/seguros/colegios'
      path: '/seguros/colegios'
      fullPath: '/seguros/colegios'
      preLoaderRoute: typeof SegurosColegiosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  IndustriasRoute: IndustriasRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  PrivacidadRoute: PrivacidadRoute,
  ProductosRoute: ProductosRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  RevisionPolizaRoute: RevisionPolizaRoute,
  ServiciosRoute: ServiciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminosRoute: TerminosRoute,
  SegurosColegiosRoute: SegurosColegiosRoute,
  SegurosCondominioRoute: SegurosCondominioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
